### ISSUE TITLE
Fingerprint values sometimes aren't set due to negative result from bitwise xor

### ISSUE THREAD

**Issue by andrewmbenton** [reklatsmasters/stun#4]
Due to the way [JavaScript handles bitwise operands](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Signed_32-bit_integers), I think the result of xor can be "negative".

This is causing the addFingerprint method to fail intermittently since the value is expected to be a positive integer. Here's the problematic line: https://github.com/reklatsmasters/stun/blob/cb84b7361d651742041f72f1ea247eb808c499e7/lib/message.js#L159

**Comment by reklatsmasters** [comment]
@andrewmbenton Thanks!
